export const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS';
export const EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND';
export const CREDENTIALS_INCORRECT = 'CREDENTIALS_INCORRECT';
export const EMAIL_SENT = 'EMAIL_SENT';
export const RESET_TOKEN_NOT_FOUND = 'RESET_TOKEN_NOT_FOUND';
export const PASSWORD_RESET = 'PASSWORD_RESET';
